/*!
 * Map Splitter
 * Copyright (c) 2026 https://github.com/brunocalado
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 3.
 */

/**
 * Border crossing tools: two extra Region Controls tools ("add crossing" / "remove crossing")
 * that let the GM curate, one grid square at a time, where the generated single-square teleport
 * regions allow crossing between adjacent generated scenes.
 *
 * The tools only appear on scenes created by this module (detected through the adjacency map the
 * splitter stores in scene flags). Edits are always applied symmetrically: a crossing cell is a
 * bidirectional link made of two one-way region pairs (departure square at each scene's physical
 * edge + passive arrival square at the same map position in the other scene), so adding creates
 * every missing square and removing deletes all four; destinations never dangle and
 * `placement: "relative"` keeps working. Only whole-region create/delete operations are used —
 * no in-place shape surgery.
 */

import { FLAG_INSETS, FLAG_NEIGHBORS, MODULE_ID, OPPOSITE_SIDE } from "./constants.js";
import { buildTeleportRegion } from "./data-splitter.js";

/** @type {string} Tool name of the "add crossing" Region Controls tool. */
const TOOL_ADD = `${MODULE_ID}-add-crossing`;

/** @type {string} Tool name of the "remove crossing" Region Controls tool. */
const TOOL_REMOVE = `${MODULE_ID}-remove-crossing`;

/** @type {"add"|"remove"|null} The currently armed tool mode. */
let mode = null;

/** @type {boolean} Whether the canvas click listener is currently attached. */
let listening = false;

/**
 * Register the border tools hooks. Called once from the module entry point during `init`.
 * @returns {void}
 */
export function registerBorderTools() {
  Hooks.on("getSceneControlButtons", onGetSceneControlButtons);
  // Visibility depends on the viewed scene, so the controls must re-render on scene changes.
  Hooks.on("canvasReady", () => ui.controls?.render());
  Hooks.on("canvasTearDown", () => deactivate());
}

/**
 * Test whether a scene was generated by this module (and therefore carries an adjacency map).
 * @param {foundry.documents.Scene|null} scene  The scene to test.
 * @returns {boolean}            True when the border tools apply to this scene.
 */
function isGeneratedScene(scene) {
  return !!scene?.getFlag(MODULE_ID, FLAG_NEIGHBORS);
}

/**
 * Inject the two border tools into the Region Controls.
 * Called from the `getSceneControlButtons` hook on every SceneControls render.
 * @param {Record<string, object>} controls  The scene controls record, keyed by control name.
 * @returns {void}
 */
function onGetSceneControlButtons(controls) {
  const regions = controls.regions;
  if (!regions?.tools) return;
  const visible = game.user.isGM && isGeneratedScene(canvas?.scene);
  const order = Object.keys(regions.tools).length;
  regions.tools[TOOL_ADD] = {
    name: TOOL_ADD,
    order,
    title: "MAPSPLITTER.Tools.AddCrossing",
    icon: "fa-solid fa-link",
    visible,
    onChange: (event, active) => (active ? activate("add") : deactivate("add"))
  };
  regions.tools[TOOL_REMOVE] = {
    name: TOOL_REMOVE,
    order: order + 1,
    title: "MAPSPLITTER.Tools.RemoveCrossing",
    icon: "fa-solid fa-link-slash",
    visible,
    onChange: (event, active) => (active ? activate("remove") : deactivate("remove"))
  };
}

/**
 * Arm a tool mode and start capturing canvas clicks.
 * @param {"add"|"remove"} next  The mode to arm.
 * @returns {void}
 */
function activate(next) {
  mode = next;
  if (!listening && canvas?.stage) {
    canvas.stage.on("pointerdown", onCanvasClick);
    listening = true;
  }
}

/**
 * Disarm the current tool mode and stop capturing canvas clicks.
 * @param {"add"|"remove"} [only]  When given, only disarm if this mode is the active one — the
 *   deactivation callback of one tool must not tear down the other tool's fresh activation.
 * @returns {void}
 */
function deactivate(only) {
  if (only && mode !== only) return;
  mode = null;
  if (listening && canvas?.stage) canvas.stage.off("pointerdown", onCanvasClick);
  listening = false;
}

/**
 * Handle an armed canvas click: resolve the clicked border grid square and apply the crossing
 * operation to both sides of the border.
 * @param {PIXI.FederatedPointerEvent} event  The pointer event from the canvas stage.
 * @returns {Promise<void>}
 */
async function onCanvasClick(event) {
  if (!mode || (event.button !== 0)) return;
  const scene = canvas.scene;
  if (!game.user.isGM || !isGeneratedScene(scene)) return;
  const point = event.getLocalPosition(canvas.stage);
  const hit = borderCellAt(scene, point);
  if (!hit) {
    ui.notifications.warn("MAPSPLITTER.Warn.ClickBorder", {localize: true});
    return;
  }
  try {
    if (mode === "add") await addCrossing(scene, hit);
    else await removeCrossing(scene, hit);
  } catch (err) {
    console.error(`${MODULE_ID} |`, err);
    ui.notifications.error(game.i18n.format("MAPSPLITTER.Error.Failed", {message: err.message}));
  }
}

/* -------------------------------------------- */
/*  Border geometry                             */
/* -------------------------------------------- */

/**
 * Test whether a point lies inside a rectangle (inclusive bounds).
 * @param {{x: number, y: number}} p  The point.
 * @param {{x: number, y: number, width: number, height: number}} rect  The rectangle.
 * @returns {boolean}            True when the point is inside the rectangle.
 */
function pointInRect(p, rect) {
  return (p.x >= rect.x) && (p.x <= rect.x + rect.width)
    && (p.y >= rect.y) && (p.y <= rect.y + rect.height);
}

/**
 * Compute the logical content rectangle of a generated scene in local canvas coordinates.
 * The overlap buffer recorded in the insets flag is stripped off, so borders resolve to the
 * original cut lines. Scenes generated before overlap support carry no insets and their content
 * rectangle equals the scene rectangle.
 * @param {foundry.documents.Scene} scene  The generated scene.
 * @returns {{x: number, y: number, width: number, height: number}}  The content rectangle.
 */
function contentRect(scene) {
  const dims = scene.dimensions;
  const insets = scene.getFlag(MODULE_ID, FLAG_INSETS) ?? {};
  const left = insets.left ?? 0;
  const top = insets.top ?? 0;
  return {
    x: dims.sceneX + left,
    y: dims.sceneY + top,
    width: scene.width - left - (insets.right ?? 0),
    height: scene.height - top - (insets.bottom ?? 0)
  };
}

/**
 * Compute the one-grid-unit departure strip of a scene on a given side, in local canvas
 * coordinates. Mirrors the square geometry used at split time: the strip hugs the physical scene
 * edge (the outer rim of the overlap buffer) and spans the whole edge, buffer corners included.
 * Depth is clamped for scenes thinner than one grid cell.
 * @param {foundry.documents.Scene} scene  The scene.
 * @param {"north"|"south"|"east"|"west"} side  The border side.
 * @returns {{x: number, y: number, width: number, height: number}}  The strip rectangle.
 */
function borderStrip(scene, side) {
  const dims = scene.dimensions;
  const w = Math.min(dims.size, scene.width);
  const h = Math.min(dims.size, scene.height);
  switch (side) {
    case "west": return {x: dims.sceneX, y: dims.sceneY, width: w, height: scene.height};
    case "east": return {x: dims.sceneX + scene.width - w, y: dims.sceneY, width: w, height: scene.height};
    case "north": return {x: dims.sceneX, y: dims.sceneY, width: scene.width, height: h};
    default: return {x: dims.sceneX, y: dims.sceneY + scene.height - h, width: scene.width, height: h};
  }
}

/**
 * Translate a local rectangle of one scene into a neighbor's local coordinates across the shared
 * border. Adjacent parts share the cut line and the border span, so positions transfer by
 * re-anchoring both axes on the logical content rectangles. Used to place arrival squares at the
 * same map position as their departure square; on legacy scenes without an overlap buffer the
 * result is clamped into the neighbor's scene rectangle, which reproduces the old mirrored
 * placement.
 * @param {foundry.documents.Scene} scene     The scene owning the rectangle.
 * @param {foundry.documents.Scene} neighbor  The linked neighbor scene.
 * @param {"north"|"south"|"east"|"west"} side  Border side of `scene` facing `neighbor`.
 * @param {{x: number, y: number, width: number, height: number}} cell  The local rectangle.
 * @returns {{x: number, y: number, width: number, height: number}}  The rectangle in the
 *   neighbor's local canvas coordinates.
 */
function mapAcrossBorder(scene, neighbor, side, cell) {
  const r = contentRect(scene);
  const n = contentRect(neighbor);
  const nDims = neighbor.dimensions;
  const out = {...cell};
  switch (side) {
    case "east":
      out.x = n.x + (cell.x - (r.x + r.width));
      out.y = n.y + (cell.y - r.y);
      break;
    case "west":
      out.x = (n.x + n.width) + (cell.x - r.x);
      out.y = n.y + (cell.y - r.y);
      break;
    case "south":
      out.x = n.x + (cell.x - r.x);
      out.y = n.y + (cell.y - (r.y + r.height));
      break;
    default: // north
      out.x = n.x + (cell.x - r.x);
      out.y = (n.y + n.height) + (cell.y - r.y);
  }
  out.x = Math.clamp(out.x, nDims.sceneX, Math.max(nDims.sceneX, nDims.sceneX + neighbor.width - out.width));
  out.y = Math.clamp(out.y, nDims.sceneY, Math.max(nDims.sceneY, nDims.sceneY + neighbor.height - out.height));
  return out;
}

/**
 * Resolve the border grid square a canvas point falls into, restricted to borders that have a
 * linked generated neighbor. Corner squares belong to two strips; the side whose scene edge is
 * closest to the click wins, which is deterministic and matches user intent.
 * @param {foundry.documents.Scene} scene  The viewed generated scene.
 * @param {{x: number, y: number}} point   The click position in canvas coordinates.
 * @returns {{side: string, neighborId: string, index: number, cell: {x: number, y: number,
 *   width: number, height: number}}|null}  The hit descriptor (index is the 1-based cell index
 *   along the border), or null when the click is not on a linked border strip.
 */
function borderCellAt(scene, point) {
  const dims = scene.dimensions;
  const neighbors = scene.getFlag(MODULE_ID, FLAG_NEIGHBORS) ?? {};
  const edgeDistance = {
    west: point.x - dims.sceneX,
    east: dims.sceneX + scene.width - point.x,
    north: point.y - dims.sceneY,
    south: dims.sceneY + scene.height - point.y
  };
  const candidates = [];
  for (const side of ["west", "east", "north", "south"]) {
    if (!neighbors[side]) continue;
    if (!pointInRect(point, borderStrip(scene, side))) continue;
    candidates.push(side);
  }
  if (!candidates.length) return null;
  const side = candidates.sort((a, b) => edgeDistance[a] - edgeDistance[b])[0];

  const strip = borderStrip(scene, side);
  const vertical = (side === "west") || (side === "east");
  const along = vertical ? point.y : point.x;
  const origin = vertical ? dims.sceneY : dims.sceneX;
  const span = vertical ? scene.height : scene.width;
  // Ceil - 1 keeps a trailing partial grid cell addressable as the last (shorter) square.
  const k = Math.clamp(Math.floor((along - origin) / dims.size), 0, Math.ceil(span / dims.size) - 1);
  const cell0 = origin + (k * dims.size);
  const cellLength = Math.min(dims.size, origin + span - cell0);
  const cell = vertical
    ? {x: strip.x, y: cell0, width: strip.width, height: cellLength}
    : {x: cell0, y: strip.y, width: cellLength, height: strip.height};
  return {side, neighborId: neighbors[side], index: k + 1, cell};
}

/**
 * Compute the neighbor's own departure square at the same border offset as a border square of the
 * current scene: the square at the neighbor's physical edge on the opposite side. Adjacent parts
 * share their perpendicular crop range, so both physical borders cover the same map interval and
 * the offset along the border transfers verbatim; only the square depth may differ when one scene
 * is thinner than a grid cell.
 * @param {foundry.documents.Scene} scene     The clicked scene.
 * @param {foundry.documents.Scene} neighbor  The linked neighbor scene.
 * @param {"north"|"south"|"east"|"west"} side  Border side of the clicked scene.
 * @param {{x: number, y: number, width: number, height: number}} cell  The clicked border square.
 * @returns {{x: number, y: number, width: number, height: number}}  The neighbor's departure
 *   square in its local canvas coordinates.
 */
function mirrorCellFor(scene, neighbor, side, cell) {
  const dims = scene.dimensions;
  const nDims = neighbor.dimensions;
  const strip = borderStrip(neighbor, OPPOSITE_SIDE[side]);
  const vertical = (side === "west") || (side === "east");
  return vertical
    ? {x: strip.x, y: nDims.sceneY + (cell.y - dims.sceneY), width: strip.width, height: cell.height}
    : {x: nDims.sceneX + (cell.x - dims.sceneX), y: strip.y, width: cell.width, height: strip.height};
}

/* -------------------------------------------- */
/*  Crossing operations                         */
/* -------------------------------------------- */

/**
 * Find the module-generated teleport region covering a border square of a scene.
 * @param {foundry.documents.Scene} scene  The scene to search.
 * @param {"north"|"south"|"east"|"west"} side  The border side.
 * @param {string} targetId      Id of the linked scene the region must reference.
 * @param {{x: number, y: number, width: number, height: number}} cell  The border square.
 * @param {boolean} [entry=false]  Match passive arrival squares instead of departure squares.
 *   Regions from splits made before one-way crossings carry no entry flag and count as departures.
 * @returns {foundry.documents.Region|null}  The region, or null when the square has none.
 */
function findCrossingRegion(scene, side, targetId, cell, entry = false) {
  const center = {x: cell.x + (cell.width / 2), y: cell.y + (cell.height / 2)};
  return scene.regions.find(region => {
    const flags = region.flags?.[MODULE_ID];
    if ((flags?.teleport !== true) || (flags.side !== side) || (flags.target !== targetId)) return false;
    if ((flags.entry === true) !== entry) return false;
    return (region.shapes ?? []).some(shape =>
      (shape.type === "rectangle") && !shape.rotation && !shape.hole && pointInRect(center, shape));
  }) ?? null;
}

/**
 * Read the single level data of a generated scene, needed to build region elevation/level refs.
 * @param {foundry.documents.Scene} scene  The scene.
 * @returns {object}             The level data.
 */
function sceneLevel(scene) {
  const level = scene.toObject().levels?.[0];
  if (!level) throw new Error(`Scene "${scene.name}" has no level data.`);
  return level;
}

/**
 * Resolve the four squares composing a bidirectional crossing cell and their existing regions.
 * The squares are: the departure at the clicked scene's physical edge (`depS`), its passive
 * arrival at the same map position in the neighbor (`arrN`), the neighbor's departure at its own
 * physical edge (`depN`), and that departure's arrival back in the clicked scene (`arrS`).
 * @param {foundry.documents.Scene} scene     The clicked scene.
 * @param {foundry.documents.Scene} neighbor  The linked neighbor scene.
 * @param {{side: string, cell: object}} hit  The border square descriptor.
 * @returns {{cells: {depS: object, arrN: object, depN: object, arrS: object},
 *   regions: {depS: foundry.documents.Region|null, arrN: foundry.documents.Region|null,
 *   depN: foundry.documents.Region|null, arrS: foundry.documents.Region|null}}}  The crossing
 *   geometry and the regions currently covering each square.
 */
function resolveCrossing(scene, neighbor, hit) {
  const oside = OPPOSITE_SIDE[hit.side];
  const depS = hit.cell;
  const arrN = mapAcrossBorder(scene, neighbor, hit.side, depS);
  const depN = mirrorCellFor(scene, neighbor, hit.side, depS);
  const arrS = mapAcrossBorder(neighbor, scene, oside, depN);
  return {
    cells: {depS, arrN, depN, arrS},
    regions: {
      depS: findCrossingRegion(scene, hit.side, neighbor.id, depS),
      arrN: findCrossingRegion(neighbor, oside, scene.id, arrN, true),
      depN: findCrossingRegion(neighbor, oside, scene.id, depN),
      arrS: findCrossingRegion(scene, hit.side, neighbor.id, arrS, true)
    }
  };
}

/**
 * Open a border crossing: create the two one-way region pairs (departure + passive arrival, one
 * pair per direction) for the clicked border cell. When some squares already exist (e.g. one was
 * deleted by hand), only the missing ones are re-created — with the id their surviving partner
 * still records in flags, so the surviving destination UUID resolves again.
 * @param {foundry.documents.Scene} scene  The clicked scene.
 * @param {{side: string, neighborId: string, index: number, cell: object}} hit  The border square
 *   descriptor.
 * @returns {Promise<void>}
 */
async function addCrossing(scene, hit) {
  const neighbor = game.scenes.get(hit.neighborId);
  if (!neighbor) {
    ui.notifications.warn("MAPSPLITTER.Warn.NeighborMissing", {localize: true});
    return;
  }
  const oside = OPPOSITE_SIDE[hit.side];
  const {cells, regions} = resolveCrossing(scene, neighbor, hit);
  if (regions.depS && regions.arrN && regions.depN && regions.arrS) {
    ui.notifications.warn("MAPSPLITTER.Warn.CrossingExists", {localize: true});
    return;
  }

  const ids = {
    depS: regions.depS?.id ?? regions.arrN?.getFlag(MODULE_ID, "mirror") ?? foundry.utils.randomID(),
    arrN: regions.arrN?.id ?? regions.depS?.getFlag(MODULE_ID, "mirror") ?? foundry.utils.randomID(),
    depN: regions.depN?.id ?? regions.arrS?.getFlag(MODULE_ID, "mirror") ?? foundry.utils.randomID(),
    arrS: regions.arrS?.id ?? regions.depN?.getFlag(MODULE_ID, "mirror") ?? foundry.utils.randomID()
  };
  const createS = [];
  const createN = [];
  if (!regions.depS) {
    createS.push(buildTeleportRegion({
      id: ids.depS, strip: cells.depS, level: sceneLevel(scene), side: hit.side, index: hit.index,
      targetSceneId: neighbor.id, targetSceneName: neighbor.name, targetRegionId: ids.arrN
    }));
  }
  if (!regions.arrS) {
    createS.push(buildTeleportRegion({
      entry: true, id: ids.arrS, strip: cells.arrS, level: sceneLevel(scene), side: hit.side, index: hit.index,
      targetSceneId: neighbor.id, targetSceneName: neighbor.name, targetRegionId: ids.depN
    }));
  }
  if (!regions.depN) {
    createN.push(buildTeleportRegion({
      id: ids.depN, strip: cells.depN, level: sceneLevel(neighbor), side: oside, index: hit.index,
      targetSceneId: scene.id, targetSceneName: scene.name, targetRegionId: ids.arrS
    }));
  }
  if (!regions.arrN) {
    createN.push(buildTeleportRegion({
      entry: true, id: ids.arrN, strip: cells.arrN, level: sceneLevel(neighbor), side: oside, index: hit.index,
      targetSceneId: scene.id, targetSceneName: scene.name, targetRegionId: ids.depS
    }));
  }
  if (createS.length) await scene.createEmbeddedDocuments("Region", createS, {keepId: true});
  if (createN.length) await neighbor.createEmbeddedDocuments("Region", createN, {keepId: true});
  ui.notifications.info("MAPSPLITTER.Info.CrossingAdded", {localize: true});
}

/**
 * Close a border crossing: delete every square of the two one-way region pairs covering the
 * clicked border cell. When the neighbor scene no longer exists, only the local squares are
 * deleted.
 * @param {foundry.documents.Scene} scene  The clicked scene.
 * @param {{side: string, neighborId: string, index: number, cell: object}} hit  The border square
 *   descriptor.
 * @returns {Promise<void>}
 */
async function removeCrossing(scene, hit) {
  const neighbor = game.scenes.get(hit.neighborId) ?? null;
  const regions = neighbor
    ? resolveCrossing(scene, neighbor, hit).regions
    : {depS: findCrossingRegion(scene, hit.side, hit.neighborId, hit.cell), arrN: null, depN: null, arrS: null};
  const idsS = [regions.depS, regions.arrS].filter(r => r).map(r => r.id);
  const idsN = [regions.depN, regions.arrN].filter(r => r).map(r => r.id);
  if (!idsS.length && !idsN.length) {
    ui.notifications.warn("MAPSPLITTER.Warn.CrossingMissing", {localize: true});
    return;
  }
  if (idsS.length) await scene.deleteEmbeddedDocuments("Region", idsS);
  if (idsN.length) await neighbor.deleteEmbeddedDocuments("Region", idsN);
  ui.notifications.info("MAPSPLITTER.Info.CrossingRemoved", {localize: true});
}
